### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by dbrgn**
...it has been a while 😄

### CODE REVIEW

**Comment by rnestler** [comment]
CI fails after the last upgrade.

**Comment by threema-danilo** [comment]
> CI fails after the last upgrade.

Yeah, the upgrade isn't done yet. I plan to continue the upgrade up to Django 4.2 LTS.

Regarding the failure, I'm a bit confused _why_ it happens, the same check works locally. But I gave up debugging yesterday.

**Comment by rnestler** [comment]
> Yeah, the upgrade isn't done yet. I plan to continue the upgrade up to Django 4.2 LTS.

If it is workable on the state of [8a93762](https://github.com/coredump-ch/interna/pull/67/commits/8a93762854cbffe3621563d5b934ee3fb30a76f4) we can also just merge it with this state as an intermediate step.

**Comment by threema-danilo** [comment]
(Oops, I commented with the wrong account 😄)

> If it is workable on the state of [8a93762](https://github.com/coredump-ch/interna/pull/67/commits/8a93762854cbffe3621563d5b934ee3fb30a76f4) we can also just merge it with this state as an intermediate step.

I'd prefer to only test the changes once, and not twice 🙂 I'll finish the updates next week. (I did some tests locally, plus the unit tests, but there could be issues with deployment setup etc that must be tested after releasing.)

**Comment by dbrgn** [comment]
@rnestler ready to merge now. I assume this is OK to merge without review 🙂

The deployment should happen automatically within a few minutes IIRC. Once deployed, I'll give it a quick test.

**Comment by rnestler** [comment]
> The deployment should happen automatically within a few minutes IIRC. Once deployed, I'll give it a quick test.

The "Profile" menu item in the logged in menu doesn't do anything. But I'm not sure if it ever did :wink: 
screenshot-20231117-101148

**Comment by dbrgn** [comment]
Doesn't look like it ever did 😂 

https://github.com/coredump-ch/interna/blob/33643463e4181d8f108eca1a6282185e8e6ab085/interna/front/templates/front/base.html#L49

**Pull request merged**
