### PR TITLE
Add Crowdfunding-Tool

### PR DESCRIPTION
**Pull request by dbrgn**
Work in progress PR that will solve #14.

TODO:

- [x] Add models
- [x] Create page that lists all projects
- [x] Create detail page for a project
- [x] Make it possible to add a funding promise
- [x] Make it possible to create a new project when logged in
- [x] Allow editing of own projects
- [x] Show progress bar on list and detail pages
- [x] Freeze project and promises once funded
- [x] Email notifications on funding
- [x] Add breadcrumbs to detail page (back to list)
- [x] Add mandatory forum thread link
- [ ] Nicer CSS?
- [x] Notification on every new promise?

### CODE REVIEW

**Comment by dbrgn** [comment]
Current status of detail page:

screenshot

@rnestler @das-g any feedback so far? :slightly_smiling_face:

**Comment by das-g** [comment]
Screenshot looks good.

Is the code ready to be reviewed, too? Description of PR says "Work in progress" ...

**Comment by dbrgn** [comment]
It's not finished yet. See TODOs in first post.

**Comment by das-g** [comment]
> Is the code ready to be reviewed, too?

> It's not finished yet. See TODOs in first post.

As code doesn't have to be feature-complete to be reviewed, that doesn't answer that question. :stuck_out_tongue:

**Comment by dbrgn** [comment]
The *existing* code is ready to be reviewed, yes :stuck_out_tongue:

**Comment by dbrgn** [comment]
Adding new projects is now implemented.

**Comment by dbrgn** [comment]
Fast fertig! :sparkles: Hier die Progress Bars auf der Übersichtsseite:

List page

Und auf der Detailseite:

Detail page

**Comment by dbrgn** [comment]
Ok, code is now ready to review, in case someone wants to take a look! (@das-g maybe?)

Notification e-mails on every new funding promise are still missing, but that's not high priority yet. I'll add them before merging.

Any suggestions are welcome now!

**Comment by dbrgn** [comment]
Rebased and ready to merge! :space_invader:

**Comment by dbrgn** [comment]
And deployed! https://interna.coredump.ch/crowdfund/

**Comment by ubruhin** [comment]
Wohooo! Very cool :ok_hand: :smiley:

**Pull request merged**
